FROM golang:bullseye

WORKDIR /usr/src/app
RUN go install github.com/githubnemo/CompileDaemon@latest

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY ./ .

CMD CompileDaemon -build="go build -o bin/graphql-server ./cmd/graphql-server/main.go" -command="./bin/graphql-server"