apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdjuno-{{ .Values.deploymentTag }}
  labels:
    app: bdjuno-{{ .Values.deploymentTag }}
    app.kubernetes.io/name: bdjuno-{{ .Values.deploymentTag }}
    app.kubernetes.io/instance: bdjuno-{{ .Values.deploymentTag }}
spec:
  selector:
    matchLabels:
      app: bdjuno-{{ .Values.deploymentTag }}
  replicas: 1
  template:
    metadata:
      labels:
        app: bdjuno-{{ .Values.deploymentTag }}
      annotations:
        checksum/bdjuno-config: {{ include (print $.Template.BasePath "/bdjuno.config.yaml") . | sha256sum }}
    spec:
      restartPolicy: Always
      initContainers:
        - name: genesis-init
          image: busybox:1.28
          command: ['wget', '-O', '/.bdjuno/genesis.json', {{ .Values.bdjuno.genesisUrl }}]
          volumeMounts:
            - name: bdjuno-home
              mountPath: "/.bdjuno"
      containers:
        - name: bdjuno
          image: {{ .Values.bdjuno.imageName }}:{{ .Values.buildTag }}
          command: ["bdjuno", "start", "--home", "/bdjuno/.bdjuno"]
          volumeMounts:
            - name: bdjuno-config-{{ .Values.deploymentTag }}
              mountPath: /bdjuno/.bdjuno/config.yaml
              subPath: config.yaml
            - name: bdjuno-home
              mountPath: /bdjuno/.bdjuno/genesis.json
              subPath: genesis.json
      volumes:
        - name: bdjuno-config-{{ .Values.deploymentTag }}
          configMap:
            name: bdjuno-config-{{ .Values.deploymentTag }}
        - name: bdjuno-home
          emptyDir: {}